name: context_theme

packages:
  - packages/**
  - examples/**

scripts:
  analyze:
    exec: dart analyze --fatal-infos
    description: Run `dart analyze` in all packages

  format:
    exec: dart format --line-length=100 ./
    description: Run `dart format` in all packages