name: material_context_theme
description: A new Flutter package project.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  context_theme:
    git:
      url: https://github.com/AlexeyKatsuro/context_theme.git
      path: packages/context_theme
      ref: v0.1.0

  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

